import BuilderPage from "@/components/BuilderPage";
import Image from "next/image";

export default function Home() {
  return (
    <BuilderPage cssStyle={"flex-col"}>
      <Image
        src="/logo.svg"
        alt="Create Next App"
        width={200}
        height={200}
      />
      <h1 className="text-4xl font-bold">Create Next App</h1>
      <p className="text-lg">Generated by create next app</p>
    </BuilderPage>
  );
}
